// <auto-generated />
using System;
using AGILE2024_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGILE2024_BE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241030221517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AGILE2024_BE.Models.Role", b =>
                {
                    b.Property<int>("Id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_role"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.User", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_user"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId_role")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("SuperiorId_user")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title_after")
                        .HasColumnType("longtext");

                    b.Property<string>("Title_before")
                        .HasColumnType("longtext");

                    b.HasKey("Id_user");

                    b.HasIndex("RoleId_role");

                    b.HasIndex("SuperiorId_user");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.User", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.User", "Superior")
                        .WithMany()
                        .HasForeignKey("SuperiorId_user");

                    b.Navigation("Role");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
